# -*- coding: utf-8 -*-
"""heat_exchanger_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBF5AKiXAfuFeidiN51mgndL5EOYARXS
"""

# Heat Exchanger Experimental Analysis
# Author: Chibuikem Ndubuisi

# This program:
# - imports temperature data
# - calculates flow rate and mass flow rate
# - calculates heat-transfer performance
# - calculates Reynolds number
# - calculates LMTD
# - calculates overall heat-transfer coefficient
# - calculates effectiveness
# - compares hot-side and cold-side energy changes
# - produces graphs


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# --------------------------------------------------
# STEP 1 - Upload and load the data
# --------------------------------------------------

from google.colab import files

uploaded = files.upload()

filename = list(uploaded.keys())[0]

data = pd.read_csv(filename)


# --------------------------------------------------
# STEP 2 - Check the data
# --------------------------------------------------

print("\nFirst 5 rows")
print("---------------------------------------------")
print(data.head())

print("\nLast 5 rows")
print("---------------------------------------------")
print(data.tail())

print("\nData size")
print("---------------------------------------------")
print(data.shape)

print("\nColumn names")
print("---------------------------------------------")
print(data.columns)

print("\nData summary")
print("---------------------------------------------")
print(data.describe())


# --------------------------------------------------
# STEP 3 - Experimental measurements
# --------------------------------------------------

hot_volume = 11.4          # litres
cold_volume = 9.0          # litres collected

run_time = data["Time"].iloc[-1]

print("\nExperimental Measurements")
print("---------------------------------------------")

print("Hot water volume:", hot_volume, "L")
print("Cold water collected:", cold_volume, "L")
print("Experiment time:", run_time, "s")


# --------------------------------------------------
# STEP 4 - Calculate flow rate
# --------------------------------------------------

flow_rate_L_min = cold_volume / (run_time / 60)

print("\nFlow rate:", flow_rate_L_min, "L/min")


# Earlier pump calibration result
calibration_flow_rate = 1.25

flow_difference = (
    abs(flow_rate_L_min - calibration_flow_rate)
    / calibration_flow_rate
) * 100

print(
    "Difference from pump calibration:",
    flow_difference,
    "%"
)


# --------------------------------------------------
# STEP 5 - Convert flow rate to m^3/s
# --------------------------------------------------

flow_rate_m3_s = flow_rate_L_min / 1000 / 60

print(
    "Flow rate:",
    flow_rate_m3_s,
    "m^3/s"
)


# --------------------------------------------------
# STEP 6 - Calculate mass flow rate
# --------------------------------------------------

rho = 1000                 # water density kg/m^3

mass_flow_rate = (
    rho * flow_rate_m3_s
)

print(
    "Mass flow rate:",
    mass_flow_rate,
    "kg/s"
)


# --------------------------------------------------
# STEP 7 - Assign sensor data
# --------------------------------------------------

# Sensor 1 = lower hot bath
# Sensor 2 = upper hot bath
# Sensor 3 = cold-water reservoir / inlet
# Sensor 4 = collection vessel

hot_lower = data["Sensor1"]
hot_upper = data["Sensor2"]
cold_inlet = data["Sensor3"]
collection = data["Sensor4"]

time = data["Time"]


# --------------------------------------------------
# STEP 8 - Calculate average hot-bath temperature
# --------------------------------------------------

hot_average = (
    hot_lower + hot_upper
) / 2

data["Hot Average"] = hot_average


initial_hot_temperature = hot_average.iloc[0]
final_hot_temperature = hot_average.iloc[-1]

hot_temperature_drop = (
    initial_hot_temperature
    - final_hot_temperature
)

print("\nHot Bath Results")
print("---------------------------------------------")

print(
    "Initial average hot-bath temperature:",
    initial_hot_temperature,
    "C"
)

print(
    "Final average hot-bath temperature:",
    final_hot_temperature,
    "C"
)

print(
    "Hot-bath temperature drop:",
    hot_temperature_drop,
    "C"
)


# --------------------------------------------------
# STEP 9 - Check difference between hot bath sensors
# --------------------------------------------------

hot_sensor_difference = (
    hot_upper - hot_lower
)

data["Hot Sensor Difference"] = hot_sensor_difference

average_hot_sensor_difference = np.mean(
    hot_sensor_difference
)

print(
    "Average difference between upper and lower hot sensors:",
    average_hot_sensor_difference,
    "C"
)


# --------------------------------------------------
# STEP 10 - Calculate cold-side temperature rise
# --------------------------------------------------

cold_temperature_rise = (
    collection - cold_inlet
)

data["Cold Temperature Rise"] = cold_temperature_rise


initial_cold_temperature = cold_inlet.iloc[0]
final_collection_temperature = collection.iloc[-1]

print("\nCold Side Results")
print("---------------------------------------------")

print(
    "Initial cold-water temperature:",
    initial_cold_temperature,
    "C"
)

print(
    "Final collection temperature:",
    final_collection_temperature,
    "C"
)

print(
    "Final measured temperature rise:",
    final_collection_temperature
    - initial_cold_temperature,
    "C"
)


# --------------------------------------------------
# STEP 11 - Calculate apparent heat-transfer rate
# --------------------------------------------------

cp = 4180                  # specific heat capacity of water J/kg.K

heat_transfer_rate = (
    mass_flow_rate
    * cp
    * cold_temperature_rise
)

data["Heat Transfer Rate"] = heat_transfer_rate


average_heat_transfer_rate = np.mean(
    heat_transfer_rate
)

maximum_heat_transfer_rate = np.max(
    heat_transfer_rate
)

print("\nHeat Transfer Rate")
print("---------------------------------------------")

print(
    "Average apparent heat-transfer rate:",
    average_heat_transfer_rate,
    "W"
)

print(
    "Maximum apparent heat-transfer rate:",
    maximum_heat_transfer_rate,
    "W"
)


# --------------------------------------------------
# STEP 12 - Copper tube dimensions
# --------------------------------------------------

tube_outer_diameter = 0.008
tube_wall_thickness = 0.0015
tube_length = 0.79

tube_inner_diameter = (
    tube_outer_diameter
    - 2 * tube_wall_thickness
)

print("\nCopper Tube")
print("---------------------------------------------")

print(
    "Tube outside diameter:",
    tube_outer_diameter,
    "m"
)

print(
    "Tube inside diameter:",
    tube_inner_diameter,
    "m"
)

print(
    "Tube length:",
    tube_length,
    "m"
)


# --------------------------------------------------
# STEP 13 - Calculate heat-transfer surface area
# --------------------------------------------------

heat_transfer_area = (
    np.pi
    * tube_outer_diameter
    * tube_length
)

print(
    "Heat-transfer surface area:",
    heat_transfer_area,
    "m^2"
)


# --------------------------------------------------
# STEP 14 - Calculate LMTD
# --------------------------------------------------

# Temperature difference between hot bath
# and collection vessel

delta_T1 = (
    hot_average - collection
)

# Temperature difference between hot bath
# and cold-water inlet

delta_T2 = (
    hot_average - cold_inlet
)


lmtd = (
    (delta_T2 - delta_T1)
    / np.log(delta_T2 / delta_T1)
)

data["LMTD"] = lmtd


average_lmtd = np.mean(lmtd)

print("\nLMTD")
print("---------------------------------------------")

print(
    "Average LMTD:",
    average_lmtd,
    "K"
)


# --------------------------------------------------
# STEP 15 - Calculate apparent overall
# heat-transfer coefficient
# --------------------------------------------------

U = (
    heat_transfer_rate
    / (heat_transfer_area * lmtd)
)

data["U"] = U


average_U = np.mean(U)

print("\nOverall Heat-Transfer Coefficient")
print("---------------------------------------------")

print(
    "Average apparent U:",
    average_U,
    "W/m^2.K"
)


# --------------------------------------------------
# STEP 16 - Calculate internal flow area
# --------------------------------------------------

flow_area = (
    np.pi
    * (tube_inner_diameter / 2) ** 2
)

print("\nFlow Area")
print("---------------------------------------------")

print(
    "Internal tube flow area:",
    flow_area,
    "m^2"
)


# --------------------------------------------------
# STEP 17 - Calculate water velocity
# --------------------------------------------------

velocity = (
    flow_rate_m3_s
    / flow_area
)

print(
    "Average water velocity:",
    velocity,
    "m/s"
)


# --------------------------------------------------
# STEP 18 - Calculate Reynolds number
# --------------------------------------------------

# Approximate water viscosity

mu = 0.00091

reynolds = (
    rho
    * velocity
    * tube_inner_diameter
    / mu
)

print("\nReynolds Number")
print("---------------------------------------------")

print(
    "Reynolds number:",
    reynolds
)


if reynolds < 2300:

    print("Flow regime: Laminar")

elif reynolds < 4000:

    print("Flow regime: Transitional")

else:

    print("Flow regime: Turbulent")


# --------------------------------------------------
# STEP 19 - Calculate Prandtl number
# --------------------------------------------------

thermal_conductivity = 0.60

prandtl = (
    cp
    * mu
    / thermal_conductivity
)

print("\nPrandtl Number")
print("---------------------------------------------")

print(
    "Prandtl number:",
    prandtl
)


# --------------------------------------------------
# STEP 20 - Calculate apparent effectiveness
# --------------------------------------------------

effectiveness = (
    (collection - cold_inlet)
    / (hot_average - cold_inlet)
)

data["Effectiveness"] = effectiveness


average_effectiveness = np.mean(
    effectiveness
)

effectiveness_percentage = (
    average_effectiveness * 100
)

print("\nHeat Exchanger Effectiveness")
print("---------------------------------------------")

print(
    "Average apparent effectiveness:",
    average_effectiveness
)

print(
    "Average apparent effectiveness:",
    effectiveness_percentage,
    "%"
)


# --------------------------------------------------
# STEP 21 - Energy calculations
# --------------------------------------------------

# Water is approximately 1 kg/L

hot_mass = hot_volume
cold_mass = cold_volume


# Energy lost by hot-water bath

hot_energy_lost = (
    hot_mass
    * cp
    * (
        initial_hot_temperature
        - final_hot_temperature
    )
)


# Approximate energy gained by the
# 9 L of collected cold water

cold_energy_gained = (
    cold_mass
    * cp
    * (
        final_collection_temperature
        - initial_cold_temperature
    )
)


energy_difference = (
    hot_energy_lost
    - cold_energy_gained
)


energy_difference_percentage = (
    abs(energy_difference)
    / hot_energy_lost
) * 100


print("\nEnergy Balance")
print("---------------------------------------------")

print(
    "Energy lost by hot bath:",
    hot_energy_lost / 1000,
    "kJ"
)

print(
    "Approximate energy gained by cold water:",
    cold_energy_gained / 1000,
    "kJ"
)

print(
    "Energy difference:",
    energy_difference / 1000,
    "kJ"
)

print(
    "Energy difference percentage:",
    energy_difference_percentage,
    "%"
)


# --------------------------------------------------
# STEP 22 - Print final results
# --------------------------------------------------

print("\n")
print("=============================================")
print("FINAL HEAT EXCHANGER RESULTS")
print("=============================================")

print(
    "Experiment time:",
    run_time,
    "s"
)

print(
    "Hot-water volume:",
    hot_volume,
    "L"
)

print(
    "Cold water collected:",
    cold_volume,
    "L"
)

print(
    "Flow rate:",
    round(flow_rate_L_min, 3),
    "L/min"
)

print(
    "Mass flow rate:",
    round(mass_flow_rate, 5),
    "kg/s"
)

print(
    "Water velocity:",
    round(velocity, 3),
    "m/s"
)

print(
    "Reynolds number:",
    round(reynolds, 0)
)

print(
    "Average apparent heat-transfer rate:",
    round(average_heat_transfer_rate, 2),
    "W"
)

print(
    "Average LMTD:",
    round(average_lmtd, 2),
    "K"
)

print(
    "Heat-transfer area:",
    round(heat_transfer_area, 5),
    "m^2"
)

print(
    "Average apparent U:",
    round(average_U, 2),
    "W/m^2.K"
)

print(
    "Average apparent effectiveness:",
    round(effectiveness_percentage, 2),
    "%"
)

print(
    "Hot-bath energy lost:",
    round(hot_energy_lost / 1000, 2),
    "kJ"
)

print(
    "Approximate cold-water energy gained:",
    round(cold_energy_gained / 1000, 2),
    "kJ"
)

print("=============================================")


# ==================================================
# PLOTS
# ==================================================


# --------------------------------------------------
# PLOT 1 - All temperatures vs time
# --------------------------------------------------

plt.figure()

plt.plot(
    time,
    hot_lower,
    label="Lower Hot Bath"
)

plt.plot(
    time,
    hot_upper,
    label="Upper Hot Bath"
)

plt.plot(
    time,
    cold_inlet,
    label="Cold Inlet"
)

plt.plot(
    time,
    collection,
    label="Collection Vessel"
)

plt.xlabel("Time (s)")
plt.ylabel("Temperature (°C)")
plt.title("Temperature vs Time")

plt.legend()
plt.grid()

plt.tight_layout()

plt.savefig(
    "temperature_vs_time.png",
    dpi=300
)

plt.show()


# --------------------------------------------------
# PLOT 2 - Average hot bath and collection vessel
# --------------------------------------------------

plt.figure()

plt.plot(
    time,
    hot_average,
    label="Average Hot Bath"
)

plt.plot(
    time,
    collection,
    label="Collection Vessel"
)

plt.xlabel("Time (s)")
plt.ylabel("Temperature (°C)")

plt.title(
    "Hot Bath and Collection Vessel Temperature"
)

plt.legend()
plt.grid()

plt.tight_layout()

plt.savefig(
    "hot_bath_vs_collection.png",
    dpi=300
)

plt.show()


# --------------------------------------------------
# PLOT 3 - Heat-transfer rate vs time
# --------------------------------------------------

plt.figure()

plt.plot(
    time,
    heat_transfer_rate
)

plt.xlabel("Time (s)")
plt.ylabel("Heat-Transfer Rate (W)")

plt.title(
    "Apparent Heat-Transfer Rate vs Time"
)

plt.grid()

plt.tight_layout()

plt.savefig(
    "heat_transfer_rate_vs_time.png",
    dpi=300
)

plt.show()


# --------------------------------------------------
# PLOT 4 - LMTD vs time
# --------------------------------------------------

plt.figure()

plt.plot(
    time,
    lmtd
)

plt.xlabel("Time (s)")
plt.ylabel("LMTD (K)")

plt.title(
    "Log Mean Temperature Difference vs Time"
)

plt.grid()

plt.tight_layout()

plt.savefig(
    "lmtd_vs_time.png",
    dpi=300
)

plt.show()


# --------------------------------------------------
# PLOT 5 - Overall U vs time
# --------------------------------------------------

plt.figure()

plt.plot(
    time,
    U
)

plt.xlabel("Time (s)")
plt.ylabel("U (W/m^2.K)")

plt.title(
    "Apparent Overall Heat-Transfer Coefficient vs Time"
)

plt.grid()

plt.tight_layout()

plt.savefig(
    "overall_U_vs_time.png",
    dpi=300
)

plt.show()


# --------------------------------------------------
# PLOT 6 - Effectiveness vs time
# --------------------------------------------------

plt.figure()

plt.plot(
    time,
    effectiveness * 100
)

plt.xlabel("Time (s)")
plt.ylabel("Effectiveness (%)")

plt.title(
    "Apparent Heat Exchanger Effectiveness vs Time"
)

plt.grid()

plt.tight_layout()

plt.savefig(
    "effectiveness_vs_time.png",
    dpi=300
)

plt.show()


# --------------------------------------------------
# PLOT 7 - Upper and lower hot-bath temperatures
# --------------------------------------------------

plt.figure()

plt.plot(
    time,
    hot_lower,
    label="Lower Hot Bath"
)

plt.plot(
    time,
    hot_upper,
    label="Upper Hot Bath"
)

plt.xlabel("Time (s)")
plt.ylabel("Temperature (°C)")

plt.title(
    "Upper and Lower Hot-Bath Temperatures"
)

plt.legend()
plt.grid()

plt.tight_layout()

plt.savefig(
    "hot_bath_temperatures.png",
    dpi=300
)

plt.show()


# --------------------------------------------------
# Save all calculated data
# --------------------------------------------------

data.to_csv(
    "heat_exchanger_calculated_data.csv",
    index=False
)

print()
print(
    "Calculated data saved as "
    "heat_exchanger_calculated_data.csv"
)